[package]
name = "languagetool-rust"
version = "0.0.15"
authors = ["Jérome Eertmans <jeertmans@icloud.com>"]
edition = "2021"
description = "LanguageTool API bindings in Rust."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jeertmans/languagetool-rust"
keywords = ["languagetool", "rust"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
annotate-snippets = { version = "0.9.1", features = ["color"], optional = true }
clap = { version = "3.1.18", features = ["derive", "cargo"], optional = true }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread"], optional = true }

[dev-dependencies]
tokio = { version = "1.18.2", features = ["macros"]}


[features]
annotate = ["annotate-snippets"]
cli = ["clap", "tokio"]
unstable = []

default = ["cli"]

[lib]
name = "languagetool_rust"
path = "src/lib/lib.rs"

[[bin]]
name = "ltrs"
path = "src/bin.rs"
required-features = ["cli", "tokio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
