[package]
name = "languagetool-rust"
version = "1.3.0"
authors = ["Jérome Eertmans <jeertmans@icloud.com>"]
edition = "2021"
description = "LanguageTool API bindings in Rust."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jeertmans/languagetool-rust"
keywords = ["languagetool", "rust"]
include = ["src/**/*", "LICENSE.md", "README.md", "CHANGELOG.md"]
rust-version = "1.57.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
annotate-snippets = { version = "^0.8.0", features = ["color"], optional = true }
atty = { version = "^0.2", optional = true }
clap = { version = "^3.0", features = ["derive", "cargo", "env"], optional = true }
clap_complete = { version = "^3.0", optional = true }
reqwest = { version = "^0.11", default-features = false, features = ["json"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "^1.0"
tokio = { version = "^1.0", features = ["macros", "rt-multi-thread"], optional = true }

[dev-dependencies]
criterion = "0.3"
futures = "0.3"
tokio = { version = "^1.0", features = ["macros"]}

[features]
annotate = ["annotate-snippets"]
cli = ["atty", "clap", "tokio"]
cli-complete = ["cli", "clap_complete"]
docker = []
full = ["annotate", "cli", "docker", "unstable", "cli-complete"]

native-tls = ["reqwest/native-tls"]
native-tls-vendored = ["reqwest/native-tls-vendored"]

unstable = []

default = ["cli", "native-tls"]

[lib]
name = "languagetool_rust"
path = "src/lib/lib.rs"

[[bin]]
name = "ltrs"
path = "src/bin.rs"
required-features = ["cli", "tokio"]

[[test]]
name = "match-positions"
path = "tests/match_positions.rs"

[[bench]]
name    = "bench_main"
path = "benches/bench_main.rs"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
