on:
  pull_request:
  workflow_dispatch:

name: CHANGELOG check

jobs:
  changelog_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dorny/paths-filter@v2
        id: changes
        with:
           filters: |
             src:
               - 'CHANGELOG.md'

        # run only if some file in 'src' folder was changed
        if: steps.changes.outputs.src == 'true'
        run: echo "LOL" && exit 1

