on:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
  workflow_dispatch:

name: Docker tests

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    env:
      LANGUAGETOOL_HOSTNAME: "http://localhost"
      LANGUAGETOOL_PORT: 8010
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      - run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - run: docker pull erikvl87/languagetool
      - run: docker run -d --rm -p 8010:8010 erikvl87/languagetool
      - run: cargo install --path . --all-features --debug
      - run: function retry { ltrs ping && echo "Server is up and running!" || (echo "Failed to ping server, retrying in 2 seconds" && sleep 2 && retry) }; retry
      - run: cat README.md | ltrs check
      - run: ltrs languages
      - run: ltrs check -t "Some text with a apparent mistake"
      - run: cargo nextest run --all-features
