on:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
  workflow_dispatch:

name: Cargo check

jobs:
  cargo_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: taiki-e/install-action@cargo-hack
